
spring:
datasource:
url: jdbc:mysql://localhost:3306/federation3?createDatabaseIfNotExist=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
username: ${dbUserName}
password: ${dbUserPasse}
driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
database: MYSQL
show-sql: false
hibernate:
ddl-auto: update
dialect: org.hibernate.dialect.MySQL5Dialect
server:
port: 7071
flickr:
apiKey: ${ApiKeyFlickr}
apiSecret: ${ApiSecretFlickr}
appKey: ${AppKeyFlickr}
appSecret: ${AppSecretFlickr}
logging:
level:
com.greta.federation: TRACE
file:
name: logs/app.log
stripe:
secretKey: ${StripSecretKey}

